In [7]:
%load_ext autoreload
%autoreload 2
# for development

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [8]:
import os
import pandas as pd
import numpy as np
from collections import defaultdict

In [9]:
extab = pd.read_pickle('extab.pkl')

In [10]:
extab

{'academische_titel':           naam  id  me  republiek  republiek_friezen  batfra  \
 0         Bac.   1   1          0                  0       0
 1          Dr.   2   1          0                  0       0
 2         Lic.   3   1          0                  0       0
 3          Mr.   4   1          0                  0       0
 4          ds.   5   0          0                  0       1
 5       mr.dr.   6   0          1                  0       1
 6     prof.dr.   7   0          0                  0       1
 7  prof.dr.mr.   8   0          0                  0       0
 8     prof.ds.   9   0          0                  0       1
 9     prof.mr.  10   0          0                  0       1

    negentiende_eeuw  divperioden
 0                 0            0
 1                 0            0
 2                 0            0
 3                 0            0
 4                 1            0
 5                 1            0
 6                 1            0
 7                 1            0
 8                 1            0
 9                 1            0  ,
 'adellijke_titel':                 naam  id  me  republiek  republiek_friezen  batfra  \
 0              baron   1   1          1                  1       1
 1     baron (Empire)   2   0          0                  0       1
 2          burggraaf   3   1          1                  0       0
 3     comte (Empire)   4   0          0                  0       1
 4   comte (d'Empire)   5   0          1                  0       0
 5       duc (Empire)   6   0          0                  0       1
 6              graaf   7   1          1                  1       1
 7               heer   8   1          0                  0       0
 8             hertog   9   1          1                  0       0
 9           jonkheer  10   1          0                  0       0
 10             knaap  11   1          0                  0       0
 11         markgraaf  12   1          0                  0       0
 12           markies  13   1          1                  0       0
 13   prince (Empire)  14   0          0                  0       1
 14             prins  15   1          1                  0       0
 15            ridder  16   1          1                  1       1

     negentiende_eeuw  divperioden
 0                  1            1
 1                  0            0
 2                  1            0
 3                  1            0
 4                  0            0
 5                  0            0
 6                  1            1
 7                  0            0
 8                  1            0
 9                  0            0
 10                 0            0
 11                 0            0
 12                 1            0
 13                 0            0
 14                 1            0
 15                 1            1  ,
 'persoon':            geslachtsnaam   tussenvoegsel         voornaam  adel  \
 0                  Röell                  Willem Frederik     1
 1               Mollerus                    Johan Hendrik     1
 2      Lodewijk Napoleon                             None     0
 3              Crommelin  van Wickevoort       Jan Pieter     0
 4               Appelius                       Jean Henry     0
 ...                  ...             ...              ...   ...
 22021         Taubenheim             von         Christof     0
 22022             Winter                      Feijo Johan     0
 22023            Ziegler                           Caspar     0
 22024          Bouricius             van          Jacobus     0
 22025          Bouricius       Crack van         Johannes     0

       adelspredikaat             heerlijkheid  geboortejaar  overlijdensjaar  \
 0               None                                 1767.0           1835.0
 1               None  Westkerke en Wulpendaal        1750.0           1834.0
 2               None                                 1778.0           1846.0
 3               None                                 1763.0           1837.0
 4               None                                 1767.0           1828.0
 ...              ...                      ...           ...              ...
 22021           None                                    NaN           1536.0
 22022           None                                    NaN              NaN
 22023           None                                    NaN           1518.0
 22024           None                                    NaN           1672.0
 22025           None                                    NaN           1700.0

                                              opmerkingen  periode  ...  \
 0      Adelspredicaat: 1815/adelstitel: 1819.\r\nOver...        2  ...
 1      Adelspredicaat: 1816/adelstitel: 1820.\r\nOver...        2  ...
 2                                                   None        2  ...
 3                                                   None        2  ...
 4      Overig: na 13 februari 1807 was Appelius zowel...        2  ...
 ...                                                  ...      ...  ...
 22021                                               None        9  ...
 22022  Persoonsgegevens: mogelijk promotie in de rech...        9  ...
 22023                                               None        9  ...
 22024      Overig: was grietman van Engwirden 1657-1672.        9  ...
 22025      Overig: was grietman van Engwirden 1677-1697.        9  ...

        overlijdensdatum                searchable  academischetitel_id  \
 0            1835-12-31                     Röell                  6.0
 1            1834-12-31                  Mollerus                  NaN
 2            1846-12-31         Lodewijk Napoleon                  NaN
 3            1837-12-31  van Wickevoort Crommelin                  NaN
 4            1828-12-31                  Appelius                  NaN
 ...                 ...                       ...                  ...
 22021        1536-12-31            von Taubenheim                  NaN
 22022              None                    Winter                  NaN
 22023        1518-12-31                   Ziegler                  NaN
 22024        1672-12-29             van Bouricius                  NaN
 22025        1700-03-27       Crack van Bouricius                  NaN

        adellijketitel_id me  republiek  republiek_friezen batfra  \
 0                    1.0  0          0                  0      1
 1                    1.0  0          0                  0      1
 2                    NaN  0          0                  0      1
 3                    NaN  0          0                  0      1
 4                    NaN  0          0                  0      1
 ...                  ... ..        ...                ...    ...
 22021                NaN  0          0                  1      0
 22022                NaN  0          0                  1      0
 22023                NaN  0          0                  1      0
 22024                NaN  0          0                  1      0
 22025                NaN  0          0                  1      0

        negentiende_eeuw divperioden
 0                     0           0
 1                     0           0
 2                     0           0
 3                     0           0
 4                     0           0
 ...                 ...         ...
 22021                 0           0
 22022                 0           0
 22023                 0           0
 22024                 0           0
 22025                 0           0

 [22026 rows x 30 columns],
 'alias':                                             naam  persoon_id  me  republiek  \
 0                              Bertrand dit Béto       121.0   0          0
 1                                   Rooie Pieter         NaN   0          0
 2            Ville-sur-Illon, Comte de Lacépède.       114.0   0          0
 3                  Verhuell, Graaf van Sevenaer.        28.0   0          0
 4     Twenth van Raephorst, Graaf van Rozenburg.        11.0   0          0
 ...                                          ...         ...  ..        ...
 1936                         Jelle van Jongestal     21585.0   0          0
 1937                           Julius van Botnia     21530.0   0          0
 1938                              Johan Rotaller     22013.0   0          0
 1939                               Petrus Wiardi     21445.0   0          0
 1940                  Van Hambroick van Weleveld     21093.0   0          0

       republiek_friezen  batfra  negentiende_eeuw  divperioden
 0                     0       1                 0            0
 1                     0       1                 0            0
 2                     0       1                 0            0
 3                     0       1                 0            0
 4                     0       1                 0            0
 ...                 ...     ...               ...          ...
 1936                  1       0                 0            0
 1937                  1       0                 0            0
 1938                  1       0                 0            0
 1939                  1       0                 0            0
 1940                  1       0                 0            0

 [1941 rows x 8 columns],
 'bron':                                                   naam   id  me  republiek  \
 0    \tPas, Wil van de, en Peet Theeuwen, Ambtenare...    1   0          1
 1    (1)Correspondentie van Willem van Oranje (1533...    2   1          0
 2    (2)Correspondentie van Willem van Oranje (1533...    3   1          0
 3    A.J. Mensema, De ridderschap van Overijssel 14...    4   0          0
 4    A.J. van der Aa, Biographisch woordenboek der ...    5   0          0
 ..                                                 ...  ...  ..        ...
 806  [Charters bij] Stukken afkomstig van het kapit...  807   1          0
 807  [Charters van de] Familie van Borssele van Bri...  808   1          0
 808  [Rekeningen] Familie van Borssele van Brigdamm...  809   1          0
 809  superintendant van de Bewapening van de Zuiderzee  810   1          0
 810   www.napoleonica.org - membres du Conseil d' État  811   0          0

      republiek_friezen  batfra  negentiende_eeuw  divperioden
 0                    0       0                 0            0
 1                    0       0                 0            0
 2                    0       0                 0            0
 3                    0       1                 0            1
 4                    0       1                 1            1
 ..                 ...     ...               ...          ...
 806                  0       0                 0            0
 807                  0       0                 0            0
 808                  0       0                 0            0
 809                  0       0                 0            0
 810                  0       1                 0            0

 [811 rows x 8 columns],
 'bron_details':                  details  bron_id  persoon_id  me  republiek  \
 0                    59.    533.0         1.0   0          0
 1               IX, 871.    511.0         1.0   0          0
 2                   173.      7.0         2.0   0          0
 3             VIII, 296.      5.0         2.0   0          0
 4                    65.    533.0         2.0   0          0
 ...                  ...      ...         ...  ..        ...
 32026      6 (1997) 286.    421.0     21392.0   0          0
 32027  6 (1997) 286-288.    421.0     21880.0   0          0
 32028  6 (1997) 288-290.    421.0     21426.0   0          0
 32029  6 (1997) 294-296.    421.0     21131.0   0          0
 32030     106 (1989) 36.    506.0     21950.0   0          0

        republiek_friezen  batfra  negentiende_eeuw  divperioden
 0                      0       1                 0            0
 1                      0       1                 0            0
 2                      0       1                 0            0
 3                      0       1                 0            0
 4                      0       1                 0            0
 ...                  ...     ...               ...          ...
 32026                  1       0                 0            0
 32027                  1       0                 0            0
 32028                  1       0                 0            0
 32029                  1       0                 0            0
 32030                  1       0                 0            0

 [32031 rows x 9 columns],
 'instelling':                                                   naam   id  \
 0    Administrateurs de la Loterie Impériale de France    1
 1                       Administrateurs der Posterijen    2
 2     Administration Générale des Poudres et Salpêtres    3
 3                          Administration des Monnaies    4
 4                Admiraliteit in Friesland (1596-1795)    5
 ..                                                 ...  ...
 530  Wetgevend Lichaam van het Bataafse Gemenebest ...  531
 531  Wetgevend Lichaam, Vergadering van Hun Hoog Mo...  532
 532  Wetgevend Lichaam, Vergadering van Hun Hoog Mo...  533
 533                                            Zeeraad  534
 534                               schout van Rotterban  535

                                            toelichting  me  republiek  \
 0                                                 None   0          0
 1    <br>https://resources.huygens.knaw.nl/bataafsf...   0          0
 2    <br>https://resources.huygens.knaw.nl/bataafsf...   0          0
 3    <br>https://resources.huygens.knaw.nl/bataafsf...   0          0
 4    <h1 id="institutionele-toelichting-admiralitei...   0          1
 ..                                                 ...  ..        ...
 530  <br>https://resources.huygens.knaw.nl/bataafsf...   0          0
 531  <br>https://resources.huygens.knaw.nl/bataafsf...   0          0
 532  <br>https://resources.huygens.knaw.nl/bataafsf...   0          0
 533  <br>https://resources.huygens.knaw.nl/bataafsf...   0          0
 534                                               None   1          0

      republiek_friezen  batfra  negentiende_eeuw  divperioden
 0                    0       1                 0            0
 1                    0       1                 0            0
 2                    0       1                 0            0
 3                    0       1                 0            0
 4                    1       0                 0            1
 ..                 ...     ...               ...          ...
 530                  0       1                 0            0
 531                  0       1                 0            0
 532                  0       1                 0            0
 533                  0       1                 0            0
 534                  0       0                 0            0

 [535 rows x 9 columns],
 'functie':                                                    naam    id  me  republiek  \
 0                    Drossaard van het Land van Heusden     1   1          0
 1                              adjunct advocaat-fiscaal     2   0          1
 2                                   adjunct archivarius     3   0          0
 3                                  adjunct chef divisie     4   0          0
 4                                  adjunct hoofdcommies     5   0          0
 ...                                                 ...   ...  ..        ...
 2158                    watergraaf van de Vijfambachten  2159   1          0
 2159                    waterklerk van de Vijfambachten  2160   1          0
 2160  zaakverzorger des Konings bij het Hof van Reke...  2161   0          0
 2161                                     zegelbewaarder  2162   1          0
 2162                          zegelbewaarder in Zeeland  2163   1          0

       republiek_friezen  batfra  negentiende_eeuw  divperioden
 0                     0       0                 0            0
 1                     1       0                 0            1
 2                     0       1                 0            0
 3                     0       1                 0            0
 4                     0       1                 0            0
 ...                 ...     ...               ...          ...
 2158                  0       0                 0            0
 2159                  0       0                 0            0
 2160                  0       1                 0            0
 2161                  0       0                 0            0
 2162                  0       0                 0            0

 [2163 rows x 8 columns],
 'lokaal':                               naam   id  me  republiek  republiek_friezen  \
 0            's Grevelduin Kapelle    1   0          0                  0
 1                    's-Gravenhage    2   0          0                  0
 2                 's-Hertogenbosch    3   0          1                  0
 3                           Aalten    4   0          0                  0
 4                          Abcoude    5   0          0                  0
 ..                             ...  ...  ..        ...                ...
 687  Zutphen (plattelandsdistrict)  688   0          0                  0
 688                     Zwartsluis  689   0          0                  0
 689                         Zweelo  690   0          0                  0
 690                        Zweeloo  691   0          0                  0
 691                         Zwolle  692   0          1                  0

      batfra  negentiende_eeuw  divperioden
 0         1                 0            0
 1         1                 1            0
 2         1                 1            0
 3         0                 1            0
 4         0                 1            0
 ..      ...               ...          ...
 687       0                 1            0
 688       1                 1            0
 689       1                 0            0
 690       0                 1            0
 691       0                 1            0

 [692 rows x 8 columns],
 'provincie':                               naam  id  me  republiek  republiek_friezen  \
 0                           Amstel   1   0          0                  0
 1                       Amstelland   2   0          0                  0
 2                           Artois   3   0          1                  0
 3              Bouches-de-l' Yssel   4   0          0                  0
 4              Bouches-de-la-Meuse   5   0          0                  0
 5                     Boven-IJssel   6   0          0                  0
 6                          Brabant   7   0          1                  0
 7   De heer van Egmond als pachter   8   1          0                  0
 8                             Delf   9   0          0                  0
 9                           Dommel  10   0          0                  0
 10                         Drenthe  11   0          0                  0
 11                            Eems  12   0          0                  0
 12                  Ems-Occidental  13   0          0                  0
 13                       Friesland  14   1          1                  1
 14                           Frise  15   0          0                  0
 15                      Gelderland  16   1          1                  0
 16                       Groningen  17   1          1                  0
 17                      Henegouwen  18   0          1                  0
 18                         Holland  19   1          1                  1
 19              Holland en Zeeland  20   0          1                  0
 20             Karel van Charolais  21   1          0                  0
 21             Landen van Overmaze  22   0          0                  0

In [18]:
ep = extab['persoon']

In [23]:
ep

,geslachtsnaam,tussenvoegsel,voornaam,adel,adelspredikaat,heerlijkheid,geboortejaar,overlijdensjaar,opmerkingen,periode,...,overlijdensdatum,searchable,academischetitel_id,adellijketitel_id,me,republiek,republiek_friezen,batfra,negentiende_eeuw,divperioden
0,Röell,,Willem Frederik,1,None,,1767.0,1835.0,Adelspredicaat: 1815/adelstitel: 1819.\r\nOver...,2,...,1835-12-31,Röell,6.0,1.0,0,0,0,1,0,0
1,Mollerus,,Johan Hendrik,1,None,Westkerke en Wulpendaal,1750.0,1834.0,Adelspredicaat: 1816/adelstitel: 1820.\r\nOver...,2,...,1834-12-31,Mollerus,NaN,1.0,0,0,0,1,0,0
2,Lodewijk Napoleon,,None,0,None,,1778.0,1846.0,None,2,...,1846-12-31,Lodewijk Napoleon,NaN,NaN,0,0,0,1,0,0
3,Crommelin,van Wickevoort,Jan Pieter,0,None,,1763.0,1837.0,None,2,...,1837-12-31,van Wickevoort Crommelin,NaN,NaN,0,0,0,1,0,0
4,Appelius,,Jean Henry,0,None,,1767.0,1828.0,Overig: na 13 februari 1807 was Appelius zowel...,2,...,1828-12-31,Appelius,NaN,NaN,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22021,Taubenheim,von,Christof,0,None,,NaN,1536.0,None,9,...,1536-12-31,von Taubenheim,NaN,NaN,0,0,1,0,0,0
22022,Winter,,Feijo Johan,0,None,,NaN,NaN,Persoonsgegevens: mogelijk promotie in de rech...,9,...,None,Winter,NaN,NaN,0,0,1,0,0,0
22023,Ziegler,,Caspar,0,None,,NaN,1518.0,None,9,...,1518-12-31,Ziegler,NaN,NaN,0,0,1,0,0,0
22024,Bouricius,van,Jacobus,0,None,,NaN,1672.0,Overig: was grietman van Engwirden 1657-1672.,9,...,1672-12-29,van Bouricius,NaN,NaN,0,0,1,0,0,0
22025,Bouricius,Crack van,Johannes,0,None,,NaN,1700.0,Overig: was grietman van Engwirden 1677-1697.,9,...,1700-03-27,Crack van Bouricius,NaN,NaN,0,0,1,0,0,0

In [29]:
ep.columnns

AttributeError: 'DataFrame' object has no attribute 'columnns'

In [64]:
dupl = ep[ep.duplicated(['geslachtsnaam','tussenvoegsel','voornaam'], keep=False)].sort_values(['geslachtsnaam','tussenvoegsel','voornaam','overlijdensjaar'])

In [65]:
def somewhere_True(x):
   if 1 in list(x):
      return 1
   else:
      return 0

In [106]:
dd = dupl[(dupl['me']==1) | (dupl['republiek_friezen']==1)].groupby(['geslachtsnaam','tussenvoegsel','voornaam','overlijdensjaar']).agg({'me':somewhere_True,'republiek_friezen':somewhere_True,'republiek':somewhere_True,'batfra':somewhere_True, 'id':list})

In [110]:
dd[(dd['batfra']==1) & (dd['republiek']==1)]

Empty DataFrame
Columns: [me, republiek_friezen, republiek, batfra, id]
Index: []

In [53]:
dd[dd['me']==1]

Empty DataFrame
Columns: [me, republiek]
Index: []

In [13]:
ppa = extab['persoon'].merge(extab['aanstelling'], left_on='id',right_on='persoon_id')

In [17]:
ppa.set_index(['id_x','geslachtsnaam','tussenvoegsel','voornaam']).sort_index()

                                                   adel adelspredikaat  \
id_x  geslachtsnaam tussenvoegsel voornaam
1     Röell                       Willem Frederik     1           None
                                  Willem Frederik     1           None
                                  Willem Frederik     1           None
                                  Willem Frederik     1           None
                                  Willem Frederik     1           None
...                                                 ...            ...
22026 Bouricius     Crack van     Johannes            0           None
                                  Johannes            0           None
                                  Johannes            0           None
                                  Johannes            0           None
                                  Johannes            0           None

                                                  heerlijkheid  geboortejaar  \
id_x  geslachtsnaam tussenvoegsel voornaam
1     Röell                       Willem Frederik                     1767.0
                                  Willem Frederik                     1767.0
                                  Willem Frederik                     1767.0
                                  Willem Frederik                     1767.0
                                  Willem Frederik                     1767.0
...                                                        ...           ...
22026 Bouricius     Crack van     Johannes                               NaN
                                  Johannes                               NaN
                                  Johannes                               NaN
                                  Johannes                               NaN
                                  Johannes                               NaN

                                                   overlijdensjaar  \
id_x  geslachtsnaam tussenvoegsel voornaam
1     Röell                       Willem Frederik           1835.0
                                  Willem Frederik           1835.0
                                  Willem Frederik           1835.0
                                  Willem Frederik           1835.0
                                  Willem Frederik           1835.0
...                                                            ...
22026 Bouricius     Crack van     Johannes                  1700.0
                                  Johannes                  1700.0
                                  Johannes                  1700.0
                                  Johannes                  1700.0
                                  Johannes                  1700.0

                                                                                       opmerkingen_x  \
id_x  geslachtsnaam tussenvoegsel voornaam
1     Röell                       Willem Frederik  Adelspredicaat: 1815/adelstitel: 1819.\r\nOver...
                                  Willem Frederik  Adelspredicaat: 1815/adelstitel: 1819.\r\nOver...
                                  Willem Frederik  Adelspredicaat: 1815/adelstitel: 1819.\r\nOver...
                                  Willem Frederik  Adelspredicaat: 1815/adelstitel: 1819.\r\nOver...
                                  Willem Frederik  Adelspredicaat: 1815/adelstitel: 1819.\r\nOver...
...                                                                                              ...
22026 Bouricius     Crack van     Johannes             Overig: was grietman van Engwirden 1677-1697.
                                  Johannes             Overig: was grietman van Engwirden 1677-1697.
                                  Johannes             Overig: was grietman van Engwirden 1677-1697.
                                  Johannes             Overig: was grietman van Engwirden 1677-1697.
                                  Johannes             Overig: was grietman van Engwirden 1677-1697.

                                                   periode_x  eindcontrole  \
id_x  geslachtsnaam tussenvoegsel voornaam
1     Röell                       Willem Frederik          2           1.0
                                  Willem Frederik          2           1.0
                                  Willem Frederik          2           1.0
                                  Willem Frederik          2           1.0
                                  Willem Frederik          2           1.0
...                                                      ...           ...
22026 Bouricius     Crack van     Johannes                 9           NaN
                                  Johannes                 9           NaN
                                  Johannes                 9           NaN
                                  Johannes                 9           NaN
                                  Johannes                 9           NaN

                                                   geboortedag  geboortemaand  \
id_x  geslachtsnaam tussenvoegsel voornaam
1     Röell                       Willem Frederik          NaN            NaN
                                  Willem Frederik          NaN            NaN
                                  Willem Frederik          NaN            NaN
                                  Willem Frederik          NaN            NaN
                                  Willem Frederik          NaN            NaN
...                                                        ...            ...
22026 Bouricius     Crack van     Johannes                 NaN            NaN
                                  Johannes                 NaN            NaN
                                  Johannes                 NaN            NaN
                                  Johannes                 NaN            NaN
                                  Johannes                 NaN            NaN

                                                   ...  provincie_id regio_id  \
id_x  geslachtsnaam tussenvoegsel voornaam         ...
1     Röell                       Willem Frederik  ...           NaN      NaN
                                  Willem Frederik  ...           NaN      NaN
                                  Willem Frederik  ...           NaN      NaN
                                  Willem Frederik  ...           NaN      NaN
                                  Willem Frederik  ...           NaN      NaN
...                                                ...           ...      ...
22026 Bouricius     Crack van     Johannes         ...          14.0      NaN
                                  Johannes         ...           NaN      NaN
                                  Johannes         ...          14.0     28.0
                                  Johannes         ...          14.0      NaN
                                  Johannes         ...           NaN     28.0

                                                   stand_id  persoon_id me_y  \
id_x  geslachtsnaam tussenvoegsel voornaam
1     Röell                       Willem Frederik       NaN         1.0    0
                                  Willem Frederik       NaN         1.0    0
                                  Willem Frederik       NaN         1.0    0
                                  Willem Frederik       NaN         1.0    0
                                  Willem Frederik       NaN         1.0    0
...                                                     ...         ...  ...
22026 Bouricius     Crack van     Johannes              NaN     22026.0    0
                                  Johannes              NaN     22026.0    0
                                  Johannes              NaN     22026.0    0
                                  Johannes              NaN     22026.0    0
                                  Johannes              NaN     22026.0    0

                                                  republiek_y  \
id_x  geslachtsnaam tussenvoegsel voornaam
1     Röell                       Willem Frederik           0
                                  Willem Frederik           0
                                  Willem Frederik           0
                                  Willem Frederik           0
                                  Willem Frederik           0
...                                                       ...
22026 Bouricius     Crack van     Johannes                  0
                                  Johannes                  0
                                  Johannes                  0
                                  Johannes                  0
                                  Johannes                  0

                                                  republiek_friezen_y  \
id_x  geslachtsnaam tussenvoegsel voornaam
1     Röell                       Willem Frederik                   0
                                  Willem Frederik                   0
                                  Willem Frederik                   0
                                  Willem Frederik                   0
                                  Willem Frederik                   0
...                                                               ...
22026 Bouricius     Crack van     Johannes                          1
                                  Johannes                          1
                                  Johannes                          1
                                  Johannes                          1
                                  Johannes                          1

                                                  batfra_y  \
id_x  geslachtsnaam tussenvoegsel voornaam
1     Röell                       Willem Frederik        1
                                  Willem Frederik        1
                                  Willem Frederik        1
                                  Willem Frederik        1
                                  Willem Frederik        1
...                                                    ...
22026 Bouricius     Crack van     Johannes               0
                                  Johannes               0
                                  Johannes               0
                                  Johannes               0
                                  Johannes               0

                                                   negentiende_eeuw_y  \
id_x  geslachtsnaam tussenvoegsel voornaam
1     Röell                       Willem Frederik                   0
                                  Willem Frederik                   0
                                  Willem Frederik                   0
                                  Willem Frederik                   0
                                  Willem Frederik                   0
...                                                               ...
22026 Bouricius     Crack van     Johannes                          0
                                  Johannes                          0
                                  Johannes                          0
                                  Johannes                          0
                                  Johannes                          0

                                                   divperioden_y
id_x  geslachtsnaam tussenvoegsel voornaam
1     Röell                       Willem Frederik              0
                                  Willem Frederik              0
                                  Willem Frederik              0
                                  Willem Frederik              0
                                  Willem Frederik              0
...                                                          ...
22026 Bouricius     Crack van     Johannes                     0
                                  Johannes                     0
                                  Johannes                     0
                                  Johannes                     0
                                  Johannes                     0

[54429 rows x 54 columns]

In [ ]:
ppa.groupby('persoon_id').agg({'geslachtsnaam':'first', 'tussenvoegsel':'first', 
                               'voornaam':'first', 'adel':'first', 'adelspredikaat':'first',
                               'heerlijkheid':'first', 'geboortejaar':'first', 'overlijdensjaar':'first', 
                               'opmerkingen_x':'first','periode_x':'first', 'geboorteplaats':'first', 
                             'id_x':'first', 'geboortedatum':'first', 'overlijdensdatum':'first',
       'searchable':'first', 'me_x':'first','republiek_x':'first', 'republiek_friezen_x':'first', 
       'batfra_x':'first', 'negentiende_eeuw_x':'first', 'divperioden_x':'first', 'begindag':, 'beginmaand',
       'beginjaar', 'einddag', 'eindmaand', 'eindjaar', 'vertegenwoordigend',
       'opmerkingen_y', 'van_als_bekend', 'tot_als_bekend', 'van', 'tot',
       'instelling_id', 'functie_id', 'lokaal_id', 'provincie_id', 'regio_id',
       'stand_id', 'persoon_id', 'me_y', 'republiek_y', 'republiek_friezen_y',
       'batfra_y', 'negentiende_eeuw_y', 'divperioden_y'})

In [71]:
extab['persoon']['mark_for_delete'] = np.where(extab['persoon']['divperioden']==1,1,0)

In [73]:
extab['persoon'][extab['persoon']['mark_for_delete']==1]

,geslachtsnaam,tussenvoegsel,voornaam,adel,adelspredikaat,heerlijkheid,geboortejaar,overlijdensjaar,opmerkingen,periode,...,searchable,academischetitel_id,adellijketitel_id,me,republiek,republiek_friezen,batfra,negentiende_eeuw,divperioden,mark_for_delete
12321,Leisnig,van,Hugo,1,None,,1465.0,1538.0,None,9,...,van Leisnig,NaN,7.0,0,0,0,0,0,1,1
12322,Botnia,,Tialingh,1,None,,NaN,1533.0,Adelstitel: ridderslag door stadhouder Floris ...,9,...,Botnia,NaN,16.0,0,0,0,0,0,1,1
12323,Mulert,,Gerard,1,None,,NaN,1538.0,Persoonsgegevens: geboren te Utrecht.\r\nOveri...,9,...,Mulert,NaN,16.0,0,0,0,0,0,1,1
12324,Naarden,van,Maarten,0,None,,1490.0,1567.0,Overig: luitenant Hoofdmannenkamer Groningen 1...,9,...,van Naarden,NaN,NaN,0,0,0,0,0,1,1
12325,Nicolai,,Everard,1,None,,1497.0,1561.0,Persoonsgegevens: het geboortejaar is mogelijk...,9,...,Nicolai,NaN,16.0,0,0,0,0,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13338,Taubenheim,von,Christof,0,None,,NaN,1536.0,None,9,...,von Taubenheim,NaN,NaN,0,0,0,0,0,1,1
13339,Winter,,Feijo Johan,0,None,,NaN,NaN,Persoonsgegevens: mogelijk promotie in de rech...,9,...,Winter,NaN,NaN,0,0,0,0,0,1,1
13340,Ziegler,,Caspar,0,None,,NaN,1518.0,None,9,...,Ziegler,NaN,NaN,0,0,0,0,0,1,1
13341,Bouricius,van,Jacobus,0,None,,NaN,1672.0,Overig: was grietman van Engwirden 1657-1672.,9,...,van Bouricius,NaN,NaN,0,0,0,0,0,1,1
13342,Bouricius,Crack van,Johannes,0,None,,NaN,1700.0,Overig: was grietman van Engwirden 1677-1697.,9,...,Crack van Bouricius,NaN,NaN,0,0,0,0,0,1,1

In [85]:
extab.keys()

dict_keys(['academische_titel', 'adellijke_titel', 'persoon', 'alias', 'bron', 'bron_details', 'instelling', 'functie', 'lokaal', 'provincie', 'regio', 'stand', 'aanstelling', ''])

In [ ]:

extab['aanstelling']['mark_for_delete'] = np.where(extab['aanstelling']['divperioden']==1,1,0)

In [75]:
extab['aanstelling'][extab['aanstelling']['divperioden']==1]

,id,id,periode,begindag,beginmaand,beginjaar,einddag,eindmaand,eindjaar,vertegenwoordigend,...,regio_id,stand_id,persoon_id,me,republiek,republiek_friezen,batfra,negentiende_eeuw,divperioden,mark_for_delete
25060,0,4,0,25.0,7.0,1499.0,NaN,NaN,1500.0,0,...,NaN,NaN,13258.0,0,0,0,0,0,1,1
25061,1,6,0,25.0,7.0,1499.0,NaN,NaN,1515.0,0,...,NaN,NaN,12644.0,0,0,0,0,0,1,1
25062,2,7,0,23.0,5.0,1501.0,NaN,NaN,1519.0,0,...,NaN,NaN,12644.0,0,0,0,0,0,1,1
25063,3,9,0,25.0,7.0,1499.0,NaN,NaN,1500.0,0,...,NaN,NaN,12652.0,0,0,0,0,0,1,1
25064,4,11,0,25.0,7.0,1499.0,NaN,NaN,1515.0,0,...,NaN,NaN,12672.0,0,0,0,0,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27883,2823,2102,1,24.0,6.0,1697.0,26.0,6.0,1698.0,0,...,NaN,NaN,13153.0,0,0,0,0,0,1,1
27884,2824,2150,1,30.0,4.0,1733.0,9.0,5.0,1734.0,0,...,NaN,NaN,13128.0,0,0,0,0,0,1,1
27885,2825,3834,1,1.0,5.0,1724.0,27.0,5.0,1725.0,0,...,21.0,NaN,13088.0,0,0,0,0,0,1,1
27886,2826,3211,1,1.0,5.0,1655.0,17.0,10.0,1657.0,0,...,21.0,NaN,13068.0,0,0,0,0,0,1,1
27887,2827,3740,1,1.0,5.0,1713.0,30.0,4.0,1715.0,0,...,NaN,NaN,13069.0,0,0,0,0,0,1,1

In [84]:
# extab['aanstelling'][(extab['aanstelling']['republiek_friezen']==1)&(extab['aanstelling']['beginjaar']>1795)]

extab['aanstelling'][(extab['aanstelling']['republiek_friezen']==1)]['beginjaar'].value_counts().to_frame().sort_index(ascending=False)

           count
beginjaar
1795.0         2
1794.0        20
1793.0         6
1792.0         9
1791.0        18
...          ...
1503.0         1
1502.0         1
1501.0         9
1500.0         6
1499.0        16

[271 rows x 1 columns]

In [86]:
checkdb = pd.read_parquet('./concordance_files/ident20241126.parquet')

In [98]:
chids = checkdb[checkdb.id_latest.notna()].sample(40)

In [99]:
chids.columns

Index(['geslachtsnaam_latest', 'geslachtsnaam_oldnew', 'id_latest',
       'id_regent_orig', 'id_oldnew'],
      dtype='object')

In [100]:
chids.merge(extab['persoon'], left_on='id_latest',right_on='id')[['geslachtsnaam','geslachtsnaam_latest', 'geslachtsnaam_oldnew', 'id_latest',
       'id_regent_orig', 'id_oldnew',]]

,geslachtsnaam,geslachtsnaam_latest,geslachtsnaam_oldnew,id_latest,id_regent_orig,id_oldnew
0,Royen,Royen,Royen,13602,republiek_304,13622
1,Dussen,Dussen,Dussen,15696,republiek_2617,15855
2,Mooker,Mooker,Mooker,14800,republiek_1506,14934
3,Boetzelaer,Boetzelaer,Boetzelaer,14980,republiek_1742,15120
4,Houttuijn,Houttuijn,Houttuijn,13867,republiek_594,13905
5,Graswinckel,Graswinckel,Graswinckel,20292,republiek_1754,15129
6,Bleyswijk,Bleyswijk,Bleyswijk,13567,republiek_264,13582
7,Triest,Triest,Triest,20915,republiek_8289,<NA>
8,Hogendorp,Hogendorp,Hogendorp,13937,republiek_666,13977
9,Deym,Deym,Deym,14341,republiek_1007,14456
10,Banga,Banga,Banga,13273,divperioden_932,13273
11,Hairwijck,Hairwijck,Hairwijck,19228,republiek_7649,<NA>
12,Keyser,Keyser,Keyser,14465,republiek_1146,14586
13,Randwijck,Randwijck,Randwijck,20520,republiek_6485,18573
14,Blom,Blom,Blom,17091,republiek_4252,17277
15,Emmius,Emmius,Emmius,17136,republiek_4328,17344
16,Boner,Boner,Boner,21962,republiek_friezen_502,<NA>
17,Burch,Burch,Burch,20578,republiek_7522,<NA>
18,Brienen,Brienen,Brienen,17486,republiek_4960,17837
19,Alphen,Alphen,Alphen,16141,republiek_3221,16328
20,Wijckel,Wijckel,Wijckel,21825,republiek_friezen_747,<NA>
21,Rommarts,Rommarts,Rommarts,21560,republiek_friezen_94,<NA>
22,Harn,Harn,Harn,19104,republiek_7497,<NA>
23,Beveren,Beveren,Beveren,13478,republiek_170,13489
24,Alstorphius,Alstorphius,Alstorphius,21270,republiek_friezen_683,<NA>
25,Sandberg,Sandberg,Sandberg,18576,republiek_6434,19196
26,Jongh van Persijn,Jongh van Persijn,Jongh van Persijn,15156,republiek_1935,15288
27,Wevort van Ossenberg,Wevort van Ossenberg,Wevort van Ossenberg,16772,republiek_3906,16971
28,Bruyn,Bruyn,Bruyn,19036,republiek_7412,<NA>
29,Nieustadt,Nieustadt,Nieustadt,14894,republiek_1609,15030
30,Rengers,Rengers,Rengers,13096,divperioden_553,13096
31,Hagha,Hagha,Hagha,13780,republiek_505,13817
32,Sloet,Sloet,Sloet,16246,republiek_3343,16437
33,Borre van Amerongen,Borre van Amerongen,Borre van Amerongen,17644,republiek_5220,18072
34,Boot,Boot,Boot,19510,republiek_8286,<NA>
35,Lynden,Lynden,Lynden,15448,republiek_2322,15600
36,Oetgens,Oetgens,Oetgens,20588,republiek_784,14089
37,Elias,Elias,Elias,13645,republiek_361,13677
38,Heeckeren tot Beurse,Heeckeren tot Beurse,Heeckeren tot Beurse,17319,republiek_4666,17612
39,Paspoort,Paspoort,Paspoort,19316,republiek_8016,<NA>

In [112]:
import json
with open('connection.json','r') as infl:
    con = json.load(infl)
    
connection_string = con['raa_old']

In [113]:
connection_string

'mysql+pymysql://rik:X0chi@localhost/raa_old'

In [117]:
webraa = pd.read_sql_table(con='mysql+pymysql://rik:X0chi@localhost/webraa', table_name='persoon')

In [119]:
concordantie = pd.read_excel('./concordance_files/ident20241126.xlsx')

In [121]:
webraa['id_reg'] = webraa['id'].apply(lambda x: f"republiek_{x}")

In [124]:
mweb = webraa[['id_reg','geslachtsnaam']].merge(concordantie, left_on='id_reg',right_on='id_regent_orig')

In [127]:
mweb

,id_reg,geslachtsnaam,Unnamed: 0,geslachtsnaam_latest,geslachtsnaam_oldnew,id_latest,id_regent_orig,id_oldnew
0,republiek_22,Bylandt,14540,Aerssen van Voshol,Aerssen van Voshol,20318.0,republiek_22,13344.0
1,republiek_23,Carnin de Staden,14612,Fremery,Fremery,13344.0,republiek_23,13345.0
2,republiek_24,Chassé,14699,Thilenius,Thilenius,13345.0,republiek_24,13346.0
3,republiek_25,Chastel,14800,Meer,Meer,13346.0,republiek_25,13347.0
4,republiek_26,Clifford,14897,Josselet,Josselet,13347.0,republiek_26,13348.0
...,...,...,...,...,...,...,...,...
7775,republiek_8393,Eekhout,20957,Gouda,Gouda,19590.0,republiek_8393,NaN
7776,republiek_8394,Jeltinga,20958,Roelefs,Roelefs,20944.0,republiek_8394,NaN
7777,republiek_8395,Bakker,20959,Sickinghe,Sickinghe,19591.0,republiek_8395,NaN
7778,republiek_8396,Rendorp,20960,Ufkens,Ufkens,20952.0,republiek_8396,NaN
7779,republiek_8397,Egmond van de Nijenburg,20961,Hoorenken thoe Lutkegast,Hoorenken thoe Lutkegast,19592.0,republiek_8397,NaN

In [126]:
mweb[mweb['geslachtsnaam']==concordantie['geslachtsnaam_latest']]

ValueError: Can only compare identically-labeled Series objects

In [128]:
webraa[webraa['geslachtsnaam']=='Fremery']

,id,adel,heerlijkheid,voornaam,tussenvoegsel,geslachtsnaam,searchable_geslachtsnaam,geboortedatum,onbepaaldgeboortedatum,geboortedatum_als_bekend,geboorteplaats,doopjaar,overlijdensdatum,onbepaaldoverlijdensdatum,overlijdensdatum_als_bekend,overlijdensplaats,adellijketitel_id,academischetitel_id,opmerkingen,id_reg
669,670,0,,Johannes Andreas,de,Fremery,de Fremery,1801-05-31,0,31-05-1801,Leiden,0.0,1865-11-19,0,19-11-1865,Leiden,NaN,NaN,None,republiek_670
2340,2341,0,,Jacobus Petrus,de,Fremery,de Fremery,1800-02-25,0,25-02-1800,Leiden,0.0,1874-08-12,0,12-08-1874,s-Gravenzande,NaN,1.0,None,republiek_2341
6254,6255,0,,Nicolaas,de,Fremery,de Fremery,1719-01-01,0,1719,None,NaN,1784-12-31,0,1784,None,NaN,NaN,None,republiek_6255
8013,8014,0,,Petrus Isaäcus,de,Fremery,de Fremery,1776-09-06,0,06-09-1776,Leiden,0.0,1862-11-25,0,25-11-1862,'s-Gravenhage,NaN,1.0,None,republiek_8014
11180,11181,0,,Johannes,de,Fremery,de Fremery,1741-01-01,0,1741,None,NaN,1819-12-31,0,1819,None,NaN,NaN,None,republiek_11181

In [131]:
persoon[persoon['geslachtsnaam']=='Fremery']

,geslachtsnaam,tussenvoegsel,voornaam,adel,adelspredikaat,heerlijkheid,geboortejaar,overlijdensjaar,opmerkingen,periode,...,searchable,academischetitel_id,adellijketitel_id,me,republiek,republiek_friezen,batfra,negentiende_eeuw,divperioden,mark_for_delete
281,Fremery,de,Petrus Isaäcus,0,None,,1776.0,1862.0,None,2,...,de Fremery,NaN,NaN,0,0,0,1,0,0,0
1784,Fremery,de,Johannes,0,None,,1741.0,1819.0,None,2,...,de Fremery,NaN,NaN,0,0,0,1,0,0,0
4306,Fremery,de,Johannes Andreas,0,None,,1801.0,1865.0,None,2,...,de Fremery,NaN,NaN,0,0,0,0,0,0,0
4619,Fremery,de,Petrus Isaäcus,0,None,,1776.0,1862.0,None,2,...,de Fremery,NaN,NaN,0,0,0,0,0,0,0
6038,Fremery,de,Jacobus Petrus,0,None,,1800.0,1874.0,None,2,...,de Fremery,NaN,NaN,0,0,0,0,0,0,0
13343,Fremery,de,Nicolaas,0,None,,1719.0,1784.0,None,1,...,de Fremery,NaN,NaN,0,1,0,0,0,0,0